site_name: Cortex CLI (corcli)
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.top
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Getting started: 
    - Installation: getting-started.md
  - Usage: usage.md

markdown_extensions:
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 